package:
  name: ace
  version: 6.4.7


build:
  preserve_egg_dir: False
    
requirements:
  build:
    - cmake >=3.9
    - vc 14 # [win and py36] 
    - vc 9  # [win and py27]
    - libstdcxx-ng
    - libgcc-ng
  run:
    - vc 14 # [win and py35]
    - vc 9  # [win and py27]
    - libstdcxx-ng
    - libgcc-ng
	
about:
  home: http://www.dre.vanderbilt.edu/~schmidt/ACE-overview.html
  license:  Apache 2.0 license
  summary: 'ADAPTIVE Communication Environment Conda recipe'

